# Change these first
owner: musikwerk-stuttgart
repo: upptime

sites:
  - name: www.musikwerk-stuttgart.de
    url: https://www.musikwerk-stuttgart.de
  - name: Online-Shop
    url: https://www.musikwerk-stuttgart.de/warenkorb/
  - name: Musikwerk Cloud
    url: https://cloud.musikwerk-stuttgart.de
  - name: Interner Bereich
    url: https://intern.musikwerk-stuttgart.de
  - name: E-Mail
    check: "tcp-ping"
    url: w01368ea.kasserver.com
    port: 25

status-website:
  cname: status.musikwerk-stuttgart.de
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/musikwerk-stuttgart/upptime/master/assets/logo-white.svg
  name: Musikwerk Status
  introTitle:
  introMessage:
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

runner: "[self-hosted, Linux, X64]"
user-agent: upptime-musikwerk-stuttgart

workflowSchedule:
  graphs: "27 0 * * *"
  responseTime: "12 23 * * *"
  staticSite: "13 1 * * *"
  summary: "47 0 * * *"
  updateTemplate: "37 0 * * *"
  updates: "51 3 * * *"
  uptime: "2/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
